src/Alerts/Alerts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, search
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home),
    path('search',search),
    path('medium/', include('medium.urls')),    
    path('youtube/', include('youtube.urls')),    
    path('reddit/', include('reddit.urls')),    
    path('linkedIn/', include('linkedIn.urls')),    
    path('admin/', admin.site.urls),
]

src/Alerts/linkedIn/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]
app_name = 'linkedIn'

src/Alerts/medium/urls.py
from django.contrib import admin
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name = 'home'),
]
app_name = 'medium'

src/Alerts/reddit/urls.py
from django.urls import path
from .views import home, new, remove

urlpatterns = [
    path('remove/', remove, name='remove'),
    path('new/', new, name='new'),
    #both urls needed as homepage without a subreddit redirects to 'learnpython' subreddit
    path('', home, name='home'),
    path('<str:subreddit>/', home, name='home'),
]
app_name = 'reddit'

src/Alerts/youtube/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]
app_name = 'youtube'

src/Alerts/linkedIn/models.py
from django.db import models
import markdown

# Create your models here.

class LinkedInPost(models.Model):
	image = models.TextField()
	body = models.TextField()
	created = models.DateTimeField()
	url = models.TextField()
	read = models.BooleanField(default = False)

	class Meta:
		ordering = ['-created']

	def __str__(self):
		return self.body[:50]

	def mark(self):
		return markdown.markdown(self.body)

	def markWithoutP(self):
		p = '<p>'
		np = '</p>'
		md = markdown.markdown(self.body)
		if md.startswith(p) and md.endswith(np): 
		    md = md[len(p):-len(np)]
		return md
		
	def makeUrl(self):
		return "https://linkedIn.com" + self.url

	def getAndUpdateReadStatus(self):
		curr = self.read
		self.read = True
		self.save()
		return curr

src/Alerts/medium/models.py
from django.db import models

# Create your models here.
class MediumNotification(models.Model):
	description = models.TextField()
	image = models.TextField()
	date = models.DateTimeField()

	class Meta:
		ordering = ['-date']

	def __str__(self):
		return self.description

src/Alerts/reddit/models.py
from django.db import models
import markdown 

# Create your models here.
class RedditPost(models.Model):
	title = models.TextField()
	body = models.TextField()
	comments = models.IntegerField()
	createdDate = models.DateField(auto_now_add = True)
	url = models.TextField()
	postId = models.CharField(max_length = 20)
	subreddit = models.CharField(max_length = 50)
	
	class Meta:
		ordering = ['-createdDate']	

	def __str__(self):
		return self.title


	def mark(self):
		return markdown.markdown(self.body)

class Pending(models.Model):
	subreddit = models.TextField()

	def __str__(self):
		return self.subreddit

src/Alerts/youtube/models.py
from django.db import models

# Create your models here.
class YoutubeNotification(models.Model):
	videoLink = models.TextField()
	read = models.BooleanField()
	image = models.TextField()
	time = models.DateTimeField()
	description = models.TextField()
	thumbnail = models.TextField()

	class Meta:
		ordering = ['-time','read','description']
		
	def __str__(self):
		return self.description

	def getVideoLink(self):
		return "https://youtube.com/" + self.videoLink
	
	def getAndUpdateReadStatus(self):
		curr = self.read
		self.read = True
		self.save()
		return curr

src/Alerts/Alerts/views.py
from django.shortcuts import render, reverse, redirect
from django.conf import settings
from django.views.decorators.http import require_http_methods
from django.db.models import Q
from reddit.models import RedditPost
from medium.models import MediumNotification
from youtube.models import YoutubeNotification
from linkedIn.models import LinkedInPost

def home(request):
	return redirect(reverse('reddit:home'))

@require_http_methods(['POST'])
def search(request):
	querry = request.POST.get('querry')
	youtubeLookup = (Q(description__contains = querry))
	mediumLookup = (Q(description__contains = querry))
	linkedInLookup = (Q(body__contains = querry))
	redditLookup = (Q(title__contains = querry)| Q(body__contains = querry) | Q(subreddit__contains = querry))

	qsYoutube = YoutubeNotification.objects.filter(youtubeLookup).distinct()
	qsMedium = MediumNotification.objects.filter(mediumLookup).distinct()
	qsLinkedIn = LinkedInPost.objects.filter(linkedInLookup).distinct()
	qsReddit = RedditPost.objects.filter(redditLookup).distinct()
	context = {}
	context['youtube'] = qsYoutube
	context['medium'] = qsMedium
	context['reddit'] = qsReddit
	context['linkedIn'] = qsLinkedIn
	context['querry'] = querry
	return render(request, "searchResults.html",context)

src/Alerts/linkedIn/views.py
from django.shortcuts import render

# Create your views here.
from .tasks import getUserNotifications
from .models import LinkedInPost
def home(request):
	# getUserNotifications.delay()
	qs = LinkedInPost.objects.all()
	return render(request, 'linkedIn/home.html', {'linkedInPosts': qs})

src/Alerts/medium/views.py
from django.shortcuts import render
from .tasks import getUserNotifications
from .mediumBot import ScraperPersonal
from .models import MediumNotification
# Create your views here.
def home(request):
	# getUserNotifications.delay()
	qs = MediumNotification.objects.all()
	return render(request, 'medium/home.html', {'mediumNotifications': qs})

src/Alerts/reddit/views.py
from django.shortcuts import render, reverse, redirect
import markdown
# Create your views here.
from .models import RedditPost, Pending
from .redditBot import RedditBot
from .tasks import checkExistance
from django.contrib import messages
from django.views.decorators.http import require_http_methods


def getDistinctSubreddits():
	return RedditPost.objects.order_by('subreddit').values_list('subreddit', flat = True).distinct()


def home(request, subreddit = None):
	#default subreddit is learnpython
	if subreddit is None:
		return redirect(reverse('reddit:home', kwargs={'subreddit':"learnpython"}))
	subreddits = getDistinctSubreddits()

	qs = RedditPost.objects.filter(subreddit = subreddit)
	return render(request, "reddit/home.html", {'redditPosts' : qs, 'subreddits': subreddits, 'subreddit' : subreddit, 'pending' : Pending.objects.all()})

@require_http_methods(['POST'])
def new(request):
	subreddit = request.POST.get('subreddit')
	curr = request.POST.get('current').strip()
	#check for empty submission
	if not subreddit:
		messages.error(request,'Please enter something')
		return redirect(reverse('reddit:home'))
	
	#Check for preexistance of subreddit
	if RedditPost.objects.filter(subreddit = subreddit):
		messages.error(request, r'The subreddit <b>%s</b> already exists'%subreddit)
		return redirect(reverse('reddit:home', kwargs={'subreddit': curr}))
	
	#Check if subreddit is already added as pending
	if not Pending.objects.filter(subreddit = subreddit):
		Pending(subreddit = subreddit).save()
		checkExistance.delay(subreddit)
		messages.success(request, r'Your request is under process...If the subreddit <b>%s</b> exists, it shall be added'%subreddit)
	else:
		messages.error(request,'Your request for the subreddit <b>%s</b> is already in pending'%subreddit)

	return redirect(reverse('reddit:home', kwargs={'subreddit': curr}))


def remove(request):
	if request.POST:
		subreddits = request.POST.getlist('subreddit')
		if len(subreddits) is 0:
			messages.error(request, 'Please select atleast one subreddit')
		else :
			for subreddit in subreddits:
				RedditPost.objects.filter(subreddit = subreddit).delete()
			messages.success(request, 'Successfully removed the selected subreddits')
		
		return redirect(reverse('reddit:home'))
	#default reddit is learnpython and so it cannot be removed	
	subreddits = list(getDistinctSubreddits())
	subreddits.remove('learnpython')

	if not subreddits:
		messages.error(request, "No subreddit to be removed...Please add some first")
		return redirect(reverse('reddit:home'))
	return render(request, "reddit/removeSubreddit.html", {'subreddits' : subreddits})

src/Alerts/youtube/views.py
from django.shortcuts import render
from .tasks import getUserNotifications
from .models import YoutubeNotification
# Create your views here.
def home(request):
	#getUserNotifications.delay()
	qs = YoutubeNotification.objects.all()
		
	return render(request, "youtube/home.html", {"youtubeNotifications": qs})

src/Alerts/linkedIn/templates/home.html
{% extends "base.html" %}
{% block content %}
	<div class="list-group">
	{% for post in linkedInPosts %}
		{% include 'includes/linkedInPost.html' with post=post %}
	{% endfor %}
		
	</div>
	
{% endblock %}

src/Alerts/linkedIn/templates/linkedIn/includes/linkedInPost.html
{% load humanize %}
<a href="{{ post.makeUrl }}" target="blank" class="list-group-item list-group-item-action flex-column align-items-center
{% if not post.getAndUpdateReadStatus %}unread{% endif %}"
>
    <div class="d-flex w-100 justify-content-between">
     <p class="mb-1" style="margin-right: 20px;">{{ post.markWithoutP | truncatewords:50}}</p>
     <span><img src="{{ post.image }}" class = "rounded" alt=""></span>
    </div>
 <span class="oi oi-calendar"></span>
      	{{ post.created | naturaltime}}
    </span>  
</a>

src/Alerts/medium/templates/medium/home.html
{% extends "base.html" %}
{% block content %}

{% if not mediumNotifications %}
	{% include 'includes/empty.html' %}
{% else %}
	<div class="list-group" style="margin: 5px;">
		{% for notification in mediumNotifications %}
			{% include 'medium/includes/mediumNotification.html' with notification=notification %}
		{% endfor %}
	</div>
{% endif %}

{% endblock %}

src/Alerts/medium/templates/medium/includes/mediumNotification.html
{% load humanize %}
<a href="#" target="blank" class="list-group-item list-group-item-action flex-column align-items-center"
>
<div class="d-flex w-100 justify-content-between">
	<p class="mb-1" style="margin-right: 20px;">{{ notification.description | safe | truncatewords:50}}</p>
	<span><img src="{{ notification.image }}" class = "rounded" height="50" width="50"></span>
</div>
<span class="oi oi-calendar"></span>
{{ notification.date | naturaltime }}
</span>  
</a>

src/Alerts/reddit/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	{% for post in redditPosts %}
		{% include 'includes/redditPost.html' with post=post %}
	{% endfor %}
</div>
{% endblock %}

src/Alerts/reddit/templates/reddit/home.html
{% extends "base.html" %}

{% block content %}
<!-- Messages -->
{% if messages %}
{% for message in messages %}
<div class="alert  {{ message.tags }} alert-dismissible fade show col-md-10 message" role="alert">
	{{ message | safe}}	
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endfor %}
{% endif %}

{% if not redditPosts %}
	{% include 'includes/empty.html' %}
{% else %}

<div class="row ">
	<!-- Displaying the reddit posts -->
	<div class="col-md-10" style="margin-top: 5px;">
		{% for post in redditPosts %}
		{% include 'reddit/includes/redditPost.html' with post=post %}
		{% endfor %}
	</div>

	<!-- Right had section -->
	<div class="col-md-2 popular-tags">
		<!-- Added subreddits in the form of tags -->
		<h4>Subreddits</h4>
		{% for sub in subreddits %}
		<a href="{% url 'reddit:home' sub %}"><span class="label label-default {% if sub == subreddit %} active-sub {% endif %}" >{{ sub }}</span></a>
		{% endfor %}

		<!-- Form to add new subreddits -->
		<form action="{% url 'reddit:new' %}" class="new-subreddit-form" method="POST">
			{% csrf_token %}
			<div class="form-group">
				<label for="newSubreddit">Enter a new Subreddit Name</label>
				<input type="text" class="form-control form-control-sm" id="newSubreddit" placeholder="Enter Subreddit" name="subreddit">
				<!-- We also send current subreddit so that user is redirected to current reddit only -->
				<input type="hidden" name="current" value="{{ subreddit }} ">
			</div>
			<button type="submit" class="btn btn-primary btn-sm">Submit</button>
		</form>

		<!-- Remove subreddits -->
		<a href ="{% url 'reddit:remove' %}" method="GET" class="remove-subreddit-button"><input type="submit" value="Remove" class="btn btn-danger btn-sm" /></a>
		
		<hr>
		<!-- Pending requests section -->
		<h4 id="pending-requests">Pending Requests</h4>
		{% if not pending %}
			<small><i>None</i></small>
		{% else %}
			{% for sub in pending %}
			<span class="label-pending" >{{ sub }}</span>
			{% endfor %}
		{% endif %}
	</div>
</div>
{% endif %}
{% endblock %}

src/Alerts/reddit/templates/reddit/removeSubreddit.html
{% extends "base.html" %}

{% block content %}
	{% if messages %}
		{% for message in messages %}
			<div class="alert {{ message.tags }} alert-dismissible fade show col-md-10 message" role="alert">
			{{ message | safe}}	
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		{% endfor %}
	{% endif %}
	<div class="row">
		<div class="col-md-12"  style="margin: 10px;">
			<h2>Select the subreddits you want to remove</h2>
		</div>
		<form action="." method="POST">
			{% csrf_token %}
			{% for subreddit in subreddits %}
				<div class="form-check" style="margin-top: 10px;">
					<input class="form-check-input" type="checkbox" name = "subreddit" value="{{ subreddit }}" id="{{ subreddit }}">
						<label class="form-check-label" for="{{subreddit}}">
							{{ subreddit }}
						</label>
				</div>
			
		{% endfor %}
		<button class="btn btn-primary" style="margin-top: 10px;">Submit</button>
		</form>
	</div>

{% endblock %}

src/Alerts/reddit/templates/redditPosts.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	{% for post in redditPosts %}
		{% include 'includes/redditPost.html' with post=post %}
	{% endfor %}
</div>
{% endblock %}

src/Alerts/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'includes/cssIncludes.html' %}
    {% block css %}
    {% endblock %}
    <title>Alerts</title>
  </head>
  <body>
    {% include 'includes/jsIncludes.html' %}
    {% include 'navbar.html' with querry=querry%}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

src/Alerts/templates/includes/cssIncludes.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
<link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap" rel="stylesheet">
<link rel="stylesheet" type = "text/css" href="{% static 'css/base.css' %}">

src/Alerts/templates/includes/empty.html
<div class="empty-page jumbotron">		
	<h1>Oops nothing to display</h1>
</div>

src/Alerts/templates/includes/jsIncludes.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/Alerts/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Alerts</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reddit:home' %}">Reddit</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'medium:home' %}">Medium</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'linkedIn:home' %}">LinkedIn</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'youtube:home' %}">Youtube</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="POST" action="/search">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="querry" value="{{ querry }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

src/Alerts/templates/searchResults.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type = "text/css" href="{% static 'youtube/css/youtube.css' %}">
{% endblock %}

{% block content %}

<div class="search-results">
	<div class="youtube-search-results">
	<h3>Youtube Search Results</h3>
	{% if not youtube %}
		<h6 class="no-result"><i>Nothing here</i></h6>
	{% else %}
		{% for result in youtube %}
			{% include 'youtube/includes/youtubeNotification.html' with notification=result %}
		{% endfor %}
	{% endif %}
</div>

<hr>
<div class="medium-search-results">
	<h3>Medium Search Results</h3>
	{% if not medium %}
		<h6 class="no-result"><i>Nothing here</i></h6>
	{% else %}

	{% for result in medium %}
	{% include 'medium/includes/mediumNotification.html' with notification=result %}
	{% endfor %}
	{% endif %}
</div>
<hr>

<div class="reddit-search-results">
	<h3>Reddit Search Results</h3>
	{% if not reddit %}
		<h6 class="no-result"><i>Nothing here</i></h6>
	{% else %}
	{% for result in reddit %}
	{% include 'reddit/includes/redditPost.html' with post=result %}
	{% endfor %}
	{% endif %}
</div>

<hr>


<div class="linkedIn-search-results">
	<h3>LinkedIn Search Results</h3>
	{% if not linkedIn %}
		<h6 class="no-result"><i>Nothing here</i></h6>
	{% else %}
	{% for result in linkedIn %}
	{% include 'linkedIn/includes/linkedInPost.html' with post=result %}
	{% endfor %}
	{% endif %}
</div>

</div>

{% endblock %}

src/Alerts/youtube/templates/youtube/home.html
{% extends "base.html" %}
{% load static %}

{% block css %}
	<link rel="stylesheet" type = "text/css" href="{% static 'youtube/css/youtube.css' %}">
{% endblock %}

{% block content %}

	{% if not youtubeNotifications %}
		{% include 'includes/empty.html' %}
	{% else %}
		{% for notification in youtubeNotifications %}
			{% include 'youtube/includes/youtubeNotification.html' with notification=notification %}
		{% endfor %}
	{% endif %}

{% endblock %}

src/Alerts/youtube/templates/youtube/includes/youtubeNotification.html
{% load humanize %}
<a href="{{ notification.getVideoLink }}" class="video-link">
	<div class="youtube-notification {% if not notification.getAndUpdateReadStatus %} unread {% endif %}">
	<div class="content">
		<div class="channel-logo-container">
			<img src="{{ notification.image }}" class = "channel-logo" alt="">
			<div class="notification-time"><small><i>{{ notification.time | naturaltime }}</i></small></div>
		</div>
		<div class="notification">{{ notification.description }}</div>
		<div class="video-thumbnail-container"><img src="{{ notification.thumbnail }}" alt="" class="video-thumbnail"></div>
	</div>
</div>
</a>